### ISSUE TITLE
recurring_transfers: `yarn test` fails on Linux: Error: More than one instance of bitcore-lib found

### ISSUE THREAD

**Issue by biafra23** [gnosis/safe-modules#28]
What do I need to do to fix the following error?

`yarn test` fails on Linux with the following error:
```
Error: More than one instance of bitcore-lib found. Please make sure to require bitcore-lib and check that submodules do not also include their own bitcore-lib dependency.
    at Object.bitcore.versionGuard (/home/biafra/safe-modules/recurring_transfers/node_modules/bitcore-mnemonic/node_modules/bitcore-lib/index.js:12:11)
    at Object.<anonymous> (/home/biafra/safe-modules/recurring_transfers/node_modules/bitcore-mnemonic/node_modules/bitcore-lib/index.js:15:9)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/biafra/safe-modules/recurring_transfers/node_modules/bitcore-mnemonic/lib/mnemonic.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/biafra/safe-modules/recurring_transfers/node_modules/bitcore-mnemonic/index.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/biafra/safe-modules/recurring_transfers/node_modules/eth-lightwallet/lib/keystore.js:8:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

  Command failed: truffle test

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

```bash
$ yarn --version
1.22.10
$ node  --version
v10.19.0
```

From yarn.lock
```
bitcore-lib@^0.15.0:
  version "0.15.0"
  resolved "https://registry.yarnpkg.com/bitcore-lib/-/bitcore-lib-0.15.0.tgz#f924be13869f2aab7e04aeec5642ad3359b6cec2"
  integrity sha512-AeXLWhiivF6CDFzrABZHT4jJrflyylDWTi32o30rF92HW9msfuKpjzrHtFKYGa9w0kNVv5HABQjCB3OEav4PhQ==
  dependencies:
    bn.js "=4.11.8"
    bs58 "=4.0.1"
    buffer-compare "=1.1.1"
    elliptic "=6.4.0"
    inherits "=2.0.1"
    lodash "=4.17.4"

bitcore-lib@^0.16.0:
  version "0.16.0"
  resolved "https://registry.yarnpkg.com/bitcore-lib/-/bitcore-lib-0.16.0.tgz#a2c3ec1108cdb90386f728282ab833e0c77c9533"
  integrity sha512-CEtcrPAH2gwgaMN+OPMJc18TBEak1+TtzMyafrqrIbK9PIa3kat195qBJhC0liJSHRiRr6IE2eLcXeIFFs+U8w==
  dependencies:
    bn.js "=4.11.8"
    bs58 "=4.0.1"
    buffer-compare "=1.1.1"
    elliptic "=6.4.0"
    inherits "=2.0.1"
    lodash "=4.17.11"

bitcore-mnemonic@^1.5.0:
  version "1.7.0"
  resolved "https://registry.yarnpkg.com/bitcore-mnemonic/-/bitcore-mnemonic-1.7.0.tgz#253295a773135e1a0b455871de614996afc8f5e1"
  integrity sha512-1JV1okgz9Vv+Y4fG2m3ToR+BGdKA6tSoqjepIxA95BZjW6YaeopVW4iOe/dY9dnkZH4+LA2AJ4YbDE6H3ih3Yw==
  dependencies:
    bitcore-lib "^0.16.0
    unorm "^1.4.1"

[...]

eth-lightwallet@^3.0.1:
  version "3.0.1"
  resolved "https://registry.yarnpkg.com/eth-lightwallet/-/eth-lightwallet-3.0.1.tgz#297022932aa568f4e4eb0873bff257f5e5b78709"
  integrity sha512-79vVCETy+4l1b6wuOWwjqPW3Bom5ZK46BgkUNwaXhiMG1rrMRHjpjYEWMqH0JHeCzOzB4HBIFz7eK1/4s6w5nA==
  dependencies:
    bitcore-lib "^0.15.0"
    bitcore-mnemonic "^1.5.0"
    buffer "^4.9.0"
    crypto-js "^3.1.5"
    elliptic "^3.1.0"
    ethereumjs-tx "^1.3.3"
    ethereumjs-util "^5.1.1"
    rlp "^2.0.0"
    scrypt-async "^1.2.0"
    tweetnacl "0.13.2"
    web3 "0.20.2"
```

**Comment by biafra23** [comment]
Adding `"resolutions": { "bitcore-lib": "0.16.0" },` to `package.json` seems to fix this problem.

**Comment by biafra23** [comment]
I made 10/11 tests work by changing one line in: `node_modules/@gnosis.pm/safe-contracts/test/utils.js`
```
const ModuleDataWrapper = (new Web3()).eth.contract([{"constant":false,"inputs":[{"name":"data","type":"bytes"}],"name":"setup","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"}]);

->

const ModuleDataWrapper = new (new Web3()).eth.Contract([{"constant":false,"inputs":[{"name":"data","type":"bytes"}],"name":"setup","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"}]);

```

```
  Contract: RecurringTransfersModule
    1) "before each" hook for "should transfer eth"

  Contract: RecurringTransfersModule
    ✓ is currently on day and between hours (71ms)
    ✓ is currently not tomorrow
    ✓ is currently not an hour in the future (60ms)
    ✓ is past month of epoch time 0
    ✓ is not past current month (72ms)
    ✓ is past previous month (164ms)
    ✓ should get correct price of token from recurring transfers module (110ms)
    ✓ should get correct price of token in token from recurring transfers module (278ms)
    ✓ should adjust transfer amount properly for $1000 in GNO tokens when there is no auction between the tokens (325ms)
    ✓ should adjust transfer amount properly for $1000 in GNO tokens when there is an auction between the tokens (188ms)


  10 passing (47s)
  1 failing

  1) Contract: RecurringTransfersModule
       "before each" hook for "should transfer eth":
     TypeError: ModuleDataWrapper.at is not a function
      at Object.createAndAddModulesData (node_modules/@gnosis.pm/safe-contracts/test/utils.js:11:32)
      at Context.<anonymous> (test/integration.js:52:43)
      at process._tickCallback (internal/process/next_tick.js:68:7)




  Command failed: truffle test

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by mikheevm** [comment]
```
~/p/g/safe-modules/recurring_transfers master !2 ❯ yarn test                                 18s Node system 16:26:47
yarn run v1.22.5
$ run-with-testrpc -l 20000000 --noVMErrorsOnRPCResponse true 'truffle test'
Create HDWalletProvider
Using gas limit: 6721.975 K
Using gas price: 5 Gwei
Optimizer enabled: false
Sign transactions using: Mnemonic
Using default mnemonic
Truffle 4
Compiling ./contracts/Imports.sol...
Compiling ./contracts/Migrations.sol...
Compiling ./contracts/RecurringTransfersModule.sol...
Compiling ./contracts/TokenPriceOracle.sol...
Compiling ./contracts/external/DateTime.sol...
Compiling ./contracts/external/DutchExchangeInterface.sol...
Compiling ./contracts/external/SafeMath.sol...
Compiling ./contracts/test/ExposedRecurringTransfersModule.sol...
Compiling @gnosis.pm/mock-contract/contracts/MockContract.sol...
Compiling @gnosis.pm/safe-contracts/contracts/GnosisSafe.sol...
Compiling @gnosis.pm/safe-contracts/contracts/base/BaseSafe.sol...
Compiling @gnosis.pm/safe-contracts/contracts/base/Executor.sol...
Compiling @gnosis.pm/safe-contracts/contracts/base/Module.sol...
Compiling @gnosis.pm/safe-contracts/contracts/base/ModuleManager.sol...
Compiling @gnosis.pm/safe-contracts/contracts/base/OwnerManager.sol...
Compiling @gnosis.pm/safe-contracts/contracts/common/Enum.sol...
Compiling @gnosis.pm/safe-contracts/contracts/common/EtherPaymentFallback.sol...
Compiling @gnosis.pm/safe-contracts/contracts/common/MasterCopy.sol...
Compiling @gnosis.pm/safe-contracts/contracts/common/SecuredTokenTransfer.sol...
Compiling @gnosis.pm/safe-contracts/contracts/common/SelfAuthorized.sol...
Compiling @gnosis.pm/safe-contracts/contracts/common/SignatureDecoder.sol...
Compiling @gnosis.pm/safe-contracts/contracts/external/SafeMath.sol...
Compiling @gnosis.pm/safe-contracts/contracts/interfaces/ISignatureValidator.sol...
Compiling @gnosis.pm/safe-contracts/contracts/libraries/CreateAndAddModules.sol...
Compiling @gnosis.pm/safe-contracts/contracts/proxies/Proxy.sol...
Compiling @gnosis.pm/safe-contracts/contracts/proxies/ProxyFactory.sol...

Compilation warnings encountered:

@gnosis.pm/safe-contracts/contracts/libraries/CreateAndAddModules.sol:12:27: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
    function enableModule(Module module)
                          ^-----------^
,@gnosis.pm/safe-contracts/contracts/libraries/CreateAndAddModules.sol:12:5: Warning: Function state mutability can be restricted to pure
    function enableModule(Module module)
    ^ (Relevant source part starts here and spans across multiple lines).



  Contract: RecurringTransfersModule
    Gas costs for create Gnosis Safe and Recurring Transfer Module: 532493
    Gas costs for add recurring transfer: 137932
    Gas costs for execute recurring transfer: 85867
    ✓ should transfer eth (869ms)
    Gas costs for create Gnosis Safe and Recurring Transfer Module: 532557
    Gas costs for add recurring transfer: 153892
    Gas costs for execute recurring transfer: 91381
    ✓ should transfer ERC20 tokens (1654ms)
    Gas costs for create Gnosis Safe and Recurring Transfer Module: 532557
    Gas costs for add recurring transfer: 137932
    Gas costs for execute recurring transfer: 86790
    ✓ should transfer eth then fail on second transfer (918ms)
    Gas costs for create Gnosis Safe and Recurring Transfer Module: 532557
    Gas costs for add recurring transfer: 137932
    Gas costs for execute recurring transfer: 87025
    Gas costs for execute recurring transfer: 83982
    ✓ should transfer eth then transfer another eth the next month (1006ms)
    Gas costs for create Gnosis Safe and Recurring Transfer Module: 532557
    Gas costs for add recurring transfer: 137932
    Gas costs for execute recurring transfer: 88150
    Gas costs for remove recurring transfer: 60248
    ✓ should transfer eth then fail the next month after the recurring transfer has been deleted (974ms)
    Gas costs for create Gnosis Safe and Recurring Transfer Module: 532429
    Gas costs for add recurring transfer: 154212
    Gas costs for execute recurring transfer: 85397
    ✓ should transfer with delegate (753ms)
    Gas costs for create Gnosis Safe and Recurring Transfer Module: 532493
    Gas costs for add recurring transfer: 137932
    ✓ should reject when rando tries to make transfer (821ms)
    Gas costs for create Gnosis Safe and Recurring Transfer Module: 532429
    Gas costs for add recurring transfer: 169276
    Gas costs for execute recurring transfer: 424415
    ✓ should transfer adjusted value of ERC20 tokens (1494ms)

  Contract: RecurringTransfersModule
    ✓ is currently on day and between hours (48ms)
    ✓ is currently not tomorrow (43ms)
    ✓ is currently not an hour in the future (52ms)
    ✓ is past month of epoch time 0
    ✓ is not past current month (127ms)
    ✓ is past previous month (171ms)
    ✓ should get correct price of token from recurring transfers module (89ms)
    ✓ should get correct price of token in token from recurring transfers module (244ms)
    ✓ should adjust transfer amount properly for $1000 in GNO tokens when there is no auction between the tokens (232ms)
    ✓ should adjust transfer amount properly for $1000 in GNO tokens when there is an auction between the tokens (169ms)


  18 passing (29s)

✨  Done in 43.63s.

```
worked for me with `"resolutions": { "bitcore-lib": "0.15.0" },` change and yarn@1.22.5, node 10.16.3

**Comment by biafra23** [comment]
@mikheevm But that was on macOS, as I understand?

**Comment by jamiegreen7** [comment]
> What do I need to do to fix the following error?
> 
> `yarn test` fails on Linux with the following error:
> 
> ```
> Error: More than one instance of bitcore-lib found. Please make sure to require bitcore-lib and check that submodules do not also include their own bitcore-lib dependency.
>     at Object.bitcore.versionGuard (/home/biafra/safe-modules/recurring_transfers/node_modules/bitcore-mnemonic/node_modules/bitcore-lib/index.js:12:11)
>     at Object.<anonymous> (/home/biafra/safe-modules/recurring_transfers/node_modules/bitcore-mnemonic/node_modules/bitcore-lib/index.js:15:9)
>     at Module._compile (internal/modules/cjs/loader.js:778:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
>     at Module.require (internal/modules/cjs/loader.js:692:17)
>     at require (internal/modules/cjs/helpers.js:25:18)
>     at Object.<anonymous> (/home/biafra/safe-modules/recurring_transfers/node_modules/bitcore-mnemonic/lib/mnemonic.js:3:15)
>     at Module._compile (internal/modules/cjs/loader.js:778:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
>     at Module.require (internal/modules/cjs/loader.js:692:17)
>     at require (internal/modules/cjs/helpers.js:25:18)
>     at Object.<anonymous> (/home/biafra/safe-modules/recurring_transfers/node_modules/bitcore-mnemonic/index.js:1:18)
>     at Module._compile (internal/modules/cjs/loader.js:778:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
>     at Module.require (internal/modules/cjs/loader.js:692:17)
>     at require (internal/modules/cjs/helpers.js:25:18)
>     at Object.<anonymous> (/home/biafra/safe-modules/recurring_transfers/node_modules/eth-lightwallet/lib/keystore.js:8:16)
>     at Module._compile (internal/modules/cjs/loader.js:778:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
> 
>   Command failed: truffle test
> 
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```
> 
>  ```shell
> $ yarn --version
> 1.22.10
> $ node  --version
> v10.19.0
> ```
> 
> From yarn.lock
> 
> ```
> bitcore-lib@^0.15.0:
>   version "0.15.0"
>   resolved "https://registry.yarnpkg.com/bitcore-lib/-/bitcore-lib-0.15.0.tgz#f924be13869f2aab7e04aeec5642ad3359b6cec2"
>   integrity sha512-AeXLWhiivF6CDFzrABZHT4jJrflyylDWTi32o30rF92HW9msfuKpjzrHtFKYGa9w0kNVv5HABQjCB3OEav4PhQ==
>   dependencies:
>     bn.js "=4.11.8"
>     bs58 "=4.0.1"
>     buffer-compare "=1.1.1"
>     elliptic "=6.4.0"
>     inherits "=2.0.1"
>     lodash "=4.17.4"
> 
> bitcore-lib@^0.16.0:
>   version "0.16.0"
>   resolved "https://registry.yarnpkg.com/bitcore-lib/-/bitcore-lib-0.16.0.tgz#a2c3ec1108cdb90386f728282ab833e0c77c9533"
>   integrity sha512-CEtcrPAH2gwgaMN+OPMJc18TBEak1+TtzMyafrqrIbK9PIa3kat195qBJhC0liJSHRiRr6IE2eLcXeIFFs+U8w==
>   dependencies:
>     bn.js "=4.11.8"
>     bs58 "=4.0.1"
>     buffer-compare "=1.1.1"
>     elliptic "=6.4.0"
>     inherits "=2.0.1"
>     lodash "=4.17.11"
> 
> bitcore-mnemonic@^1.5.0:
>   version "1.7.0"
>   resolved "https://registry.yarnpkg.com/bitcore-mnemonic/-/bitcore-mnemonic-1.7.0.tgz#253295a773135e1a0b455871de614996afc8f5e1"
>   integrity sha512-1JV1okgz9Vv+Y4fG2m3ToR+BGdKA6tSoqjepIxA95BZjW6YaeopVW4iOe/dY9dnkZH4+LA2AJ4YbDE6H3ih3Yw==
>   dependencies:
>     bitcore-lib "^0.16.0
>     unorm "^1.4.1"
> 
> [...]
> 
> eth-lightwallet@^3.0.1:
>   version "3.0.1"
>   resolved "https://registry.yarnpkg.com/eth-lightwallet/-/eth-lightwallet-3.0.1.tgz#297022932aa568f4e4eb0873bff257f5e5b78709"
>   integrity sha512-79vVCETy+4l1b6wuOWwjqPW3Bom5ZK46BgkUNwaXhiMG1rrMRHjpjYEWMqH0JHeCzOzB4HBIFz7eK1/4s6w5nA==
>   dependencies:
>     bitcore-lib "^0.15.0"
>     bitcore-mnemonic "^1.5.0"
>     buffer "^4.9.0"
>     crypto-js "^3.1.5"
>     elliptic "^3.1.0"
>     ethereumjs-tx "^1.3.3"
>     ethereumjs-util "^5.1.1"
>     rlp "^2.0.0"
>     scrypt-async "^1.2.0"
>     tweetnacl "0.13.2"
>     web3 "0.20.2"
> ```
